# Generated by Django 3.0.5 on 2020-04-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_category_cat_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_parent',
            new_name='cat_parent_id',
        ),
    ]
