# Generated by Django 3.0.5 on 2020-04-19 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20200419_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_parent_id',
            field=models.ForeignKey(blank=True, db_column='cat_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Category'),
        ),
    ]
