# Generated by Django 3.0.5 on 2020-04-20 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20200419_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_flg_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200, unique=True)),
                ('post_slug', models.SlugField(max_length=200, unique=True)),
                ('post_content', models.TextField()),
                ('post_status', models.BooleanField(default=True)),
                ('post_dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_dt_lastupd', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_flg_active', models.BooleanField(default=True)),
                ('post_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.Category')),
            ],
            options={
                'ordering': ['-post_dt_creation'],
            },
        ),
    ]
