# Generated by Django 3.0.5 on 2020-04-20 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20200420_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_cat_id',
        ),
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.ForeignKey(blank=True, db_column='cat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
