# Generated by Django 3.0.5 on 2020-04-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_post_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tags',
            new_name='tags',
        ),
    ]
