# Generated by Django 3.0.5 on 2020-04-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0010_auto_20200421_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author_id',
            field=models.ForeignKey(blank=True, db_column='post_author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_usr_lastupd',
            field=models.ForeignKey(blank=True, db_column='post_usr_lastupd_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_content', models.TextField()),
                ('com_status', models.BooleanField(default=True)),
                ('com_dt_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('com_dt_lastupd', models.DateTimeField(default=django.utils.timezone.now)),
                ('com_flg_active', models.BooleanField(default=True)),
                ('com_usr_lastupd', models.ForeignKey(blank=True, db_column='com_usr_lastupd_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments_updated', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Post')),
                ('usr_id', models.ForeignKey(blank=True, db_column='usr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
