# Generated by Django 3.0.5 on 2020-04-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0011_auto_20200421_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_dt_last_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_usr_last_publication',
            field=models.ForeignKey(blank=True, db_column='post_usr_creation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
